### ISSUE TITLE
Sample code is not working

### ISSUE THREAD

**Issue by mlampe71** [pietrobr/node-red-contrib-azure-iot-central#4]
Hi pietrobr,
as I could see you samples 1-4 are containing only one node (the IoT Central node) but not more. Could remember that the sample code was complete last time when I looked at it. Maybe something went wrong when you updated the code for the Sense-Hat samples.
Can you please take a look at it? Would be great.

Thanks 
Marco

**Comment by pietrobr** [comment]
Hi Marco,
yes, thank you for finding it. I will fix it in a future update, you can find the old version, the right one in the history, previous commit as workaround in the meantime.
Thank you again and sorry for the late response.
-Pietro

**Comment by pietrobr** [comment]
Hi Marco,
I've update the flow from 0 to 4.1  (the latest is new), and also there's a new version of the library 1.5 that fix a bug.
To pass reported props you have to simply create a JSON string and send to IoT Central node as it was a standard telemetry, but of course must have a specific format, you can find a sample also in the readme. Let me know if you have any problems.

**Comment by pietrobr** [comment]
solved
