### ISSUE TITLE
Desired property settings always "undefined"

### ISSUE THREAD

**Issue by packnology** [pietrobr/node-red-contrib-azure-iot-central#5]
Hi, this might be a problem with the IOT Central setup, but when I update a desired property in IOT Central the node logs the change to that property, but the value is "undefined", so it never registers the handler function. Is there a reason why the node is not able to read the desired property value?

**Comment by pietrobr** [comment]
Hi, yes you find a bug :-), I fix it and now a new library 1.5.0 is available and it should work. Let me know in case of any problems.

**Comment by pietrobr** [comment]
solved
